export const GET_LATEST_TERMS_AND_CONDITIONS_REQUESTED =
  'GET_LATEST_TERMS_AND_CONDITIONS_REQUESTED' as const;
export const GET_LATEST_TERMS_AND_CONDITIONS_SUCCEEDED =
  'GET_LATEST_TERMS_AND_CONDITIONS_SUCCEEDED' as const;
export const GET_LATEST_TERMS_AND_CONDITIONS_FAILED =
  'GET_LATEST_TERMS_AND_CONDITIONS_FAILED' as const;

export const GET_LATEST_ACCEPTED_TERMS_AND_CONDITIONS_REQUESTED =
  'GET_LATEST_ACCEPTED_TERMS_AND_CONDITIONS_REQUESTED' as const;
export const GET_LATEST_ACCEPTED_TERMS_AND_CONDITIONS_SUCCEEDED =
  'GET_LATEST_ACCEPTED_TERMS_AND_CONDITIONS_SUCCEEDED' as const;
export const GET_LATEST_ACCEPTED_TERMS_AND_CONDITIONS_FAILED =
  'GET_LATEST_ACCEPTED_TERMS_AND_CONDITIONS_FAILED' as const;

export const ACCEPT_TERMS_AND_CONDITIONS_REQUESTED =
  'ACCEPT_TERMS_AND_CONDITIONS_REQUESTED' as const;
export const ACCEPT_TERMS_AND_CONDITIONS_SUCCEEDED =
  'ACCEPT_TERMS_AND_CONDITIONS_SUCCEEDED' as const;
export const ACCEPT_TERMS_AND_CONDITIONS_FAILED =
  'ACCEPT_TERMS_AND_CONDITIONS_FAILED' as const;
